export const PRODUCT_LIST__REQUEST = 'PRODUCT_LIST__REQUEST';
export const PRODUCT_LIST__SUCCESS = 'PRODUCT_LIST__SUCCESS';
export const PRODUCT_LIST__FAIL = 'PRODUCT_LIST__FAIL';

export const PRODUCT_DETAIL__REQUEST = 'PRODUCT_DETAIL__REQUEST';
export const PRODUCT_DETAIL__SUCCESS = 'PRODUCT_DETAIL__SUCCESS';
export const PRODUCT_DETAIL__FAIL = 'PRODUCT_DETAIL__FAIL';
